version: '3.1'
services:
#  redis-server:
#    image: redis:5-alpine
#    container_name: redis_task_queue

#  ga-service:
#    build: ./ga-service
#    restart: always
#    container_name: ga_service
#    environment:
##      - REDIS_URL=redis://redis_task_queue
#      - DATABASE_TYPE=MONGODB
#      - DATABASE_IP=mongodb
#      - DATABASE_PORT=27017
#      - DATABASE_USER=ga-service
#      - DATABASE_PASSWORD=ga-service
#      - ENVIRONMENT=PROD
#      - BOOTSTRAP=False
#
#  api-service:
#    build: ./prediction-service
#    restart: always
#    container_name: prediction-service
#    ports:
#      - 8001:8000
#    environment:
#      SANIC_MOTOR_URI: mongodb://ga-service:ga-service@mongodb:27017/sensors?authSource=admin
#      SANIC_COLL_INDIVIDUALS: individuals
#      SANIC_COLL_CONFIG: config
#      SANIC_COLL_DATA: data

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - 27018:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ga-service
      MONGO_INITDB_ROOT_PASSWORD: ga-service

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8082:8081
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ga-service
      ME_CONFIG_MONGODB_ADMINPASSWORD: ga-service
